### ISSUE TITLE
This project makes a simlink that need to be removed for automatic_updates module

### ISSUE THREAD

**Issue by romulasry** [pantheon-systems/drupal-composer-managed#33]
The active directory at "/code" contains symlinks, which is not supported. The first one is "/code/vendor/pantheon-upstreams/upstream-configuration". See [the help page](https://dev-fugcompany.pantheonsite.io/admin/help/package_manager#package-manager-faq-symlinks-found) for information on how to resolve the problem.

Needed for https://www.drupal.org/project/automatic_updates

Tried rm -f /code/vendor/pantheon-upstreams/upstream-configuration but that didn't remove it so I am posting the bug here.

**Comment by greg-1-anderson** [comment]
`upstream-configuration` is a [path repository](https://getcomposer.org/doc/05-repositories.md#path). If you want to get rid of it, you can remove it from your top-level composer.json file. Just remove it from the `require` section and run `composer update`, and Composer will stop making these symlinks. This should be innocuous on sites that are using the "Drupal (Composer Managed)" upstream directly. Sites that are using a custom upstream will likely need to keep using the upstream-configuration path repository to work correctly.

Perhaps a better solution would be to see if the automatic updates project could support path repositories. Perhaps this particular type of symlink could be safely ignored.

**Comment by romulasry** [comment]
Okay, opened a feature request here: https://www.drupal.org/project/automatic_updates/issues/3346863

**Comment by phenaproxima** [comment]
This is already being worked on as it is required for inclusion in core. See https://www.drupal.org/project/automatic_updates/issues/3319507 for the progress there.

**Comment by phenaproxima** [comment]
For the record...it is possible to force Composer to NOT symlink path repositories. I know of two ways:

1. In the repository configuration (in composer.json), you can set an option:
```
"repositories": {
  "repo-name": {
    "type": "path",
    "url": "/path/to/repo",
    "options": {"symlink": false}
  }
}
```
2. When running `composer require` (or, presumably, `composer update`), you can pass the COMPOSER_MIRROR_PATH_REPOS environment variable to force mirroring, rather than symlinking. For example:
```
COMPOSER_MIRROR_PATH_REPOS=1 composer update pantheon-upstreams/upstream-configuration
```

**Comment by greg-1-anderson** [comment]
Thanks for the workaround, @phenaproxima. Mirroring the upstream-configuration path repository should work fine for the platform upstream and most custom upstreams.
